name: Pylint

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pync
      - name: Analysing the code with pylint
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, '*.py') }}
        run: |
          pylint $(git ls-files '*.py')
